### ISSUE TITLE
报错 

### ISSUE THREAD

**Issue by goxofy** [leonunix/hardseedGO#4]
```
2019/04/02 18:18:38 hardseedGO
2019/04/02 18:18:38 0.2
2019/04/02 18:18:38 leon.unix
2019/04/02 18:18:38 一共需要请求 6 页
2019/04/02 18:18:38 http://h3.cnmbtgf.rocks/pw/thread-htm-fid-22-page-1.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x667449]

goroutine 1 [running]:
github.com/hardseedGO/utils.Get(0xc420077290, 0xc42001c080, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/usr0102412/go/src/github.com/hardseedGO/utils/http.go:80 +0x2c9
github.com/hardseedGO/xp.Do(0x742516, 0x11)
        C:/Users/usr0102412/go/src/github.com/hardseedGO/xp/xp1024.go:50 +0x5e4
main.main()
        C:/Users/usr0102412/go/src/github.com/hardseedGO/main.go:94 +0x690
```

**Comment by ahcheqiu** [comment]
同样的问题，难受，你用的是socks代理吗
